version: '3.8'

services:
  # 1. Database: PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: order_restaurant_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: order_restaurant
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - restaurant_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d order_restaurant"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend: NestJS + Prisma
  backend:
    build: ./backend
    container_name: order_restaurant_api
    restart: always
    depends_on:
      postgres:
        condition: service_healthy 
    environment:
     DATABASE_URL="postgres://26a1d49bbc05cfb30dfb57b1c7b3e20b7ffee08f809a2e5fd8ea4cf10c76f8f8:sk_cFmIJUUifUVAORYFEHSQO@db.prisma.io:5432/postgres?uselibpqcompat=true&sslmode=require"
      PORT: 8080
    ports:
      - "8080:8080"
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"
    networks:
      - restaurant_network

  # 3. Frontend: React (Nginx)
  frontend:
    build: ./frontend
    container_name: order_restaurant_ui
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80" 
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge

volumes:
  db_data: